// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/safmeh-screens/Dashboard.tsx": () => import("../components/mockups/safmeh-screens/Dashboard.tsx"),
  "./components/mockups/safmeh-screens/SafeWalk.tsx": () => import("../components/mockups/safmeh-screens/SafeWalk.tsx"),
  "./components/mockups/safmeh-screens/SilentSOS.tsx": () => import("../components/mockups/safmeh-screens/SilentSOS.tsx")
};
